### ISSUE TITLE
Export tool tries to insert a dictionary into the the database during sync

### ISSUE THREAD

**Issue by bderenzi** [dimagi/commcare-export#100]
Version: 0.22.3-113-g807cb42

The export tool tries to insert a dictionary into the DB and SqlAlchemy throws an error `sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'`. The details of the call are too verbose to reproduce, but an example of the offending code is trying to fetch the `hh_member_register.ccs_record.ccs_record.case.index.parent` property from the register household form (XMLNS: `756ec44475658f3f463f8012632def2bc9fbe731`). An example piece of data would be:

```python
'hh_member_register.ccs_record.ccs_record.case.index.parent': {
    '#text': '901376ba-cf61-486a-9bf9-669192a75859',
    '@case_type': 'person',
    '@relationship': 'child',
    'id': '716edbb0-a845-401b-974c-41699a36311b.form.hh_member_register.ccs_record.ccs_record.case.index.parent'
},
```

From the schema export, this is marked as a `string`, as seen in the snippet below:

```json
{
    "datatype": "string", 
    "doc_type": "ScalarItem", 
    "inferred": false, 
    "inferred_from": [], 
    "label": "#form/hh_member_register/ccs_record/ccs_record/case/index/parent", 
    "last_occurrences": {
        "48cc1709b7f62ffea24cc6634a004745": 11077
    }, 
    "path": [
        {
            "doc_type": "PathNode", 
            "is_repeat": false, 
            "name": "form"
        }, 
        {
            "doc_type": "PathNode", 
            "is_repeat": false, 
            "name": "hh_member_register"
        }, 
        {
            "doc_type": "PathNode", 
            "is_repeat": false, 
            "name": "ccs_record"
        }, 
        {
            "doc_type": "PathNode", 
            "is_repeat": false, 
            "name": "ccs_record"
        }, 
        {
            "doc_type": "PathNode", 
            "is_repeat": false, 
            "name": "case"
        }, 
        {
            "doc_type": "PathNode", 
            "is_repeat": false, 
            "name": "index"
        }, 
        {
            "doc_type": "PathNode", 
            "is_repeat": false, 
            "name": "parent"
        }
    ], 
    "tag": null, 
    "transform": null
}, 
```

It is entirely possible that I should not be trying to fetch this type of data, but as far as I can tell there is no clear way to know that a field will have dictionary data a priori. Proposed next steps:
1. Catch the exception or check to make sure incoming data is not an offending datatype that will cause SqlAlchemy to choke.
1. Figure out some way to tell my script that this node will result in data that will not work with the database so that it is not added to the Excel query file.

**Comment by czue** [comment]
This is an awkward result of XML and JSON not being 100% 1:1 and us doing an unexpected transformation in processing whenever a scalar xml node also has attributes (in this case something like `<parent id="foo" case_type="person" relationship="child" >901376ba-cf61-486a-9bf9-669192a75859</parent>`)

I think we could theoretically add logic somewhere that tries to map a `dict` to `value['#text']` which would somewhat mirror what [HQ is doing here](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/export/models/new.py#L285).

**Comment by bderenzi** [comment]
Thanks, @czue. Working on a fix and it seems to be ok when there is a `#text` key in the dictionary. What should we do when there is not? For example:

```python
'hh_member_register.person.case.index.mother': {
    '@case_type': '', 
    '@relationship': 'child', 
    'id': 'c83c05d9-e06a-4457-9739-86475fc1ddc5.form.hh_member_register.person.case.index.mother'
}
```

HQ seems to just [ignore the dictionary](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/export/models/new.py#L289) in that case. Is that the correct behavior?

**Comment by czue** [comment]
yeah that seems right to me. In that case the node probably looked like:
`
<parent id="foo" case_type="" relationship="child" ></parent>
`
so is right/fine to return empty

**Comment by snopoke** [comment]
This seems like an issue with the schema generation and not with the export tool. The schema should append `#text` to the path.

**Comment by snopoke** [comment]
Looks like this should already be doing that: https://github.com/dimagi/commcare-hq/blob/9c6dd3a5338604211a8ca9c57abff4d8f5004e77/corehq/apps/export/models/new.py#L1842:L1850

Will have to dig into it to see why it's not in this case.

**Comment by czue** [comment]
> Will have to dig into it to see why it's not in this case.

@snopoke maybe save to case? (just a guess)

**Comment by snopoke** [comment]
Could be that this is using `save_to_case`

**Comment by bderenzi** [comment]
Ok. I did submit a PR #101, but didn't ask for code review because I don't think I did the DB test correctly (though not sure I understand why). Sounds like this client-side fix might not be the best place for it.

I'll keep using this patch in the short term.

**Comment by czue** [comment]
I'll defer to @snopoke on whether he wants to use the patch in the interim or has an alternate suggestion. Sounds like you're not blocked either way.
