### ISSUE TITLE
Switch to using date added to ES

### ISSUE THREAD

**Issue by bderenzi** [dimagi/commcare-export#107]
There is a bug where any unprocessed form that is in the backlog for ES will never be sync'd to a just-completed sync because we use form submission date as opposed to the data added to ES.

The proposal is to switch to using date-added-to-ES so that backlog forms will be sync'd as well.

**Comment by snopoke** [comment]
Another reason to do this is that it will prevent the tool from getting stuck when there is more than 'batch-size' docs with the same modified on date e.g. cases updated by a large case import.

**Comment by snopoke** [comment]
https://github.com/dimagi/commcare-hq/pull/24393

**Comment by snopoke** [comment]
Fixed by https://github.com/dimagi/commcare-export/pull/159
