### ISSUE TITLE
Update version of openpyxl

### ISSUE THREAD

**Issue by Naledi-OpF** [dimagi/commcare-export#109]
We are using Alteryx in order to generate the export templates we use with the export tool. When using these .xlsx templates the export tool returns the error 'Sheet has no "Data Source" column'. It seems that older versions of openpyxl can load the workbook and the sheets but do not recognise any values. Newer versions of openpyxl, which are currently not supported by the export tool, are however able to recognise values created with Alteryx.

**Comment by snopoke** [comment]
This was upgraded here: https://github.com/dimagi/commcare-export/pull/117
