### ISSUE TITLE
Running commcare-export tool on python 2.7 to MS sql server error message

### ISSUE THREAD

**Issue by yozgoesdigital** [dimagi/commcare-export#115]
When I use the commcare-export tool on python 2.7 to MS sql server it seems to give the following error:
"SAWarning: Unicode type received non-unicode bind param value"
(unfortunately I did not safe the complete error message and already made changes to the system so I cannot reproduce)
It looks like the script does in the end finalize normally. From what I find on the error message it could be somehow solved by adding unicode()
Running the on the same system using python 3.6 it looks like the error is not produced.
In case relavant running on (K)ubuntu 18.04

**Comment by snopoke** [comment]
This is just an warning and not an error. Also python 2.7 will reach end of soon.
