### ISSUE TITLE
Need ability to specify table schema used by SQL writer

### ISSUE THREAD

**Issue by tobiasmcnulty** [dimagi/commcare-export#155]
A customer is placing the data in a separate SQL Server schema and the provided user does not have permission on `dbo` to create the `alembic_version` table.

I've tested this manually by adding `version_table_schema` to `configure()` in `migrations/env.py`. That appears to do the trick.

https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.configure

Ideally it would be possible to specify this value as a command-line argument.

(We can probably make a PR for this as well, just filing for any comments in the meantime.)

**Comment by orangejenny** [comment]
Pinging @snopoke @czue in case you have thoughts on this.

For context, @tobiasmcnulty is working with one of our US COVID projects.

**Comment by czue** [comment]
Hi @tobiasmcnulty ! :wave: Nice to see you here.

I'm not too familiar with the migration internals, but in general having command line arguments to specify where the version table lives makes sense. Happy to defer to you whether you want to just implement `version_table_schema` or also support specifying other arguments like `version_table` etc., depending on the specific project needs and the effort required.

**Comment by snopoke** [comment]
This seems OK to me.

**Comment by tobiasmcnulty** [comment]
Thanks, @orangejenny @czue @snopoke !

We discovered that we also need to set the schema everywhere that any table is referenced in the code, so we'll probably make a PR with a more generic `--db-schema` (or similar) command-line argument. In SQL Server at least, it does not appear to be possible to specify the schema in some sort of global way (the way one can, for example, by setting `search_path` in Postgres): https://stackoverflow.com/a/4942223

Please let us know if you have any questions/concerns, otherwise, @benjaminEwhite at Caktus is looking into this currently, so please expect a PR from him or me soon!

**Comment by tobiasmcnulty** [comment]
It turns out that constricting sqlalchemy to a single schema (that is not the user's default schema with SQL Server) is a non-trivial project, so we've gone another route for now: https://stackoverflow.com/a/4942223
