### ISSUE TITLE
Confusing Docstring; Vulnerability?

### ISSUE THREAD

**Issue by this-vidor** [dimagi/commcare-export#50]
The docstring for [`commcare_hq_client.get`](https://github.com/dimagi/commcare-export/blob/master/commcare_export/commcare_hq_client.py#L79) reads:

```
Currently a bit of a vulnerable stub that works
for this particular use case in the hands of a trusted user; would likely
want this to work like (or via) slumber.
```

What is the meaning of "vulnerable" (and "trusted") in this docstring, and how does `slumber` address this "vulnerability"?

**Comment by snopoke** [comment]
It's not a 'vulnerability' - it just means that it's not very robust to bad user input. The is still just querying the CommCare HQ API.

Slumber would just add better validation to the URL.
